# Generated by Django 5.1.6 on 2025-03-06 10:05

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_image_videofile_rubric"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=mptt.fields.TreeForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="blog.rubric"
            ),
        ),
    ]
